export const NAIROBI_AREAS = [
  'CBD',
  'Westlands',
  'Kilimani',
  'Karen',
  'Eastleigh',
  'Parklands',
  'Upper Hill',
  'Lavington',
  'South B',
  'South C',
  'Kasarani',
  'Ruiru',
  'Embakasi',
  'Donholm',
  'Buruburu',
  'Ngong Road',
  'Lang\'ata',
  'Industrial Area',
  'Gigiri',
  'Runda',
]